# fly.toml app configuration file generated for lnbits-telegram-bot on 2023-05-31T09:41:06-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lnbits-telegram-bot"
primary_region = "lax"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
